# Examining Racial Discrimination in the US Job Market

### Background
Racial discrimination continues to be pervasive in cultures throughout the world. Researchers examined the level of racial discrimination in the United States labor market by randomly assigning identical résumés to black-sounding or white-sounding names and observing the impact on requests for interviews from employers.

### Data
In the dataset provided, each row represents a resume. The 'race' column has two values, 'b' and 'w', indicating black-sounding and white-sounding. The column 'call' has two values, 1 and 0, indicating whether the resume received a call from employers or not.

Note that the 'b' and 'w' values in race are assigned randomly to the resumes when presented to the employer.

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
data = pd.io.stata.read_stata('data/us_job_market_discrimination.dta')

In [3]:
# number of callbacks for black-sounding names
sum(data[data.race=='b'].call)

157.0

In [4]:
data.head()

id ad  education  ofjobs  yearsexp  honors  volunteer  military  empholes  \
0  b  1          4       2         6       0          0         0         1   
1  b  1          3       3         6       0          1         1         0   
2  b  1          4       1         6       0          0         0         0   
3  b  1          3       4         6       0          1         0         1   
4  b  1          3       3        22       0          0         0         0   

   occupspecific    ...      compreq  orgreq  manuf  transcom  bankreal trade  \
0             17    ...          1.0     0.0    1.0       0.0       0.0   0.0   
1            316    ...          1.0     0.0    1.0       0.0       0.0   0.0   
2             19    ...          1.0     0.0    1.0       0.0       0.0   0.0   
3            313    ...          1.0     0.0    1.0       0.0       0.0   0.0   
4            313    ...          1.0     1.0    0.0       0.0       0.0   0.0   

  busservice othservice  missind  ownership  
0        0.0        0.0      0.0             
1        0.0        0.0      0.0             
2        0.0        0.0      0.0             
3        0.0        0.0      0.0             
4        0.0        1.0      0.0  Nonprofit  

[5 rows x 65 columns]

What test is appropriate for this problem? Does CLT apply?

In [5]:
data['race'].groupby(data['race']).count()

race
b    2435
w    2435
Name: race, dtype: int64

Determining a confidence interval for the difference in population means and using a hypothesis test is appropriate. CLT applies as this distribution of callbacks should be normally distributed; the sample size is large and is of a population.

In [6]:
data['call'].groupby(data['race']).mean()

race
b    0.064476
w    0.096509
Name: call, dtype: float32

In [7]:
data['call'].groupby(data['race']).std()

race
b    0.245650
w    0.295349
Name: call, dtype: float32

What are the null and alternate hypotheses?

Null hypotheses: Race has no impact on resume callbacks. Alternative hypotheses: Race has an impact on resume callbacks.

Compute margin of error, confidence interval, and p-value.

In [8]:
### margin of error, 95% confidence interval
1.96 * ((((0.245650**2) / 2435) + ((0.295349**2) / 2435)) ** 0.5)

0.015258537778256509

In [9]:
### if we were to accept the null hypotheses, we would expect this 95% confidence interval centered around 0
### difference in means should be no more than: [-0.015, 0.015]

In [10]:
### p value is 0 given the result below
(0.064476 - 0.096509) / ((((0.245650**2) / 2435) + ((0.295349**2) / 2435)) ** 0.5)

-4.1147245504394565

Write a story describing the statistical significance in the context or the original problem.

Because we observed a difference in means outside of the 95% confidence level (0.064476 - 0.096509 = -0.032033), we reject the null hypotheses and come to the conclusion that race is a factor in resume callbacks.

Does your analysis mean that race/name is the most important factor in callback success? Why or why not? If not, how would you amend your analysis?

With a p value of 0 and a difference in means observed to be outside the confidence interval significantly, while race/name may not be the most important factor in callback success, it is a significant one. Other analysis could be performed on the data, such as: male vs. female as a factor, resume callbacks in cities vs. rural areas, etc.